name = "inma-election-dryrun"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "VOTES"
id = "8ed043e3095a464595f17e6577be5c0e"
preview_id = "8ed043e3095a464595f17e6577be5c0e"
